openapi: 3.0.0
info:
  title: fukuoka-mitou
  version: 0.1.0

paths:

  /auth:
    $ref: ./paths/user/auth.yaml
  /history:
    $ref: ./paths/user/history.yaml

  /places:
    $ref: ./paths/places.yaml

  /reserve:
    $ref: ./paths/reserve/reserve.yaml
  /cancel:
    $ref: ./paths/reserve/cancel.yaml

  /system/enter:
    $ref: ./paths/system/enter.yaml
  /system/exit:
    $ref: ./paths/system/exit.yaml

  /admin/users:
    $ref: ./paths/admin/users.yaml
  /admin/organizations:
    $ref: ./paths/admin/organizations.yaml
  /admin/places:
    $ref: ./paths/admin/places.yaml
  /admin/metrics:
    $ref: ./paths/admin/metrics.yaml