openapi: 3.0.0
info:
  title: fukuoka-mitou
  version: 0.1.0

paths:

  /auth:
    $ref: ./paths/auth.yaml
  /places:
    $ref: ./paths/places.yaml

  /me/reserve:
    $ref: ./paths/me/reserve.yaml
  /me/cancel:
    $ref: ./paths/me/cancel.yaml
  /me/history:
    $ref: ./paths/me/history.yaml

  /system/enter:
    $ref: ./paths/system/enter.yaml
  /system/exit:
    $ref: ./paths/system/exit.yaml

  /admin/users:
    $ref: ./paths/admin/users.yaml
  /admin/places:
    $ref: ./paths/admin/places.yaml
