openapi: 3.0.0
info:
  title: fukuoka-mitou
  version: 0.1.0

paths:

  /auth:
    $ref: ./paths/user/auth.yaml
  /history:
    $ref: ./paths/user/history.yaml

  /places:
    $ref: ./paths/places.yaml

  /reserve:
    $ref: ./paths/reserve/reserve.yaml
  /reserve/cancel:
    $ref: ./paths/reserve/cancel.yaml
  /reserve/attributes:
    $ref: ./paths/reserve/attributes.yaml
  /reserve/list:
    $ref: ./paths/reserve/list.yaml

  /system/enter:
    $ref: ./paths/system/enter.yaml
  /system/exit:
    $ref: ./paths/system/exit.yaml
  /system/organizations:
    $ref: ./paths/system/organizations.yaml
  /system/organizations/resolve:
    $ref: ./paths/system/resolve_organization.yaml

  /admin/users:
    $ref: ./paths/admin/users.yaml
  /admin/attributes:
    $ref: ./paths/admin/attributes.yaml
  /admin/organizations:
    $ref: ./paths/admin/organizations.yaml
  /admin/places:
    $ref: ./paths/admin/places.yaml
  /admin/approve:
    $ref: ./paths/admin/approve.yaml
  /admin/metrics:
    $ref: ./paths/admin/metrics.yaml