openapi: 3.0.0
info:
  title: fukuoka-mitou
  version: 0.1.0
paths:

  /auth:
    $ref: ./paths/auth.yaml
  
  /me/reserve:
    $ref: ./paths/me/reserve.yaml
  /me/enter:
    $ref: ./paths/me/enter.yaml
  /me/history:
    $ref: ./paths/me/history.yaml
