name: openapi
on: 
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Generate docs
      run: |
        make redocly
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./openapi

    - name: Deploy to github pages
      uses: actions/deploy-pages@v4
      id: deployment
      with:
        branch: ${{ github.head_ref }}